#!/bin/bash

## For example: $0 /tmp/inputdownloading

## Checking args
if [ $# -ne 4 ]
then
  echo "Usage: $0 landsat_X PPPRRR YYYY-MM-DD inputdownloading_path"
  exit 1
fi

## args
IMAGE_DATASET=$1
IMAGE_PATHROW=$2
IMAGE_DATE=$3
INPUTDOWNLOADING_DIR_PATH=$4

METADATA_FILE_PATH=$INPUTDOWNLOADING_DIR_PATH/stage.metadata
rm -rf $METADATA_FILE_PATH
touch $METADATA_FILE_PATH

B1_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B1.TIF")
B2_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B2.TIF")
B3_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B3.TIF")
B4_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B4.TIF")
B5_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B5.TIF")
B6_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B6.TIF")
B6_VCID_1_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B6_VCID_1.TIF")
B6_VCID_2_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B6_VCID_2.TIF")
B7_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B7.TIF")
B8_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B8.TIF")
B9_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B9.TIF")
B10_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B10.TIF")
B11_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B11.TIF")
BQA_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_BQA.TIF")
MTL_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_MTL.txt")
STATION_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_station.csv")
ELEVATION_RASTER_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "$IMAGE_PATHROW.tif")

CURRENT_DATE=$(date)

echo "# Inputdownload (googleapis) Implementation Metadata" >> $METADATA_FILE_PATH
echo "$CURRENT_DATE # Date" >> $METADATA_FILE_PATH

echo "INPUT" >> $METADATA_FILE_PATH
echo "$IMAGE_DATASET # Image Dataset" >> $METADATA_FILE_PATH
echo "$IMAGE_PATHROW # Image Pathrow" >> $METADATA_FILE_PATH
echo "$IMAGE_DATE # Image date" >> $METADATA_FILE_PATH

echo "OUTPUT" >> $METADATA_FILE_PATH
echo "$B1_INPUTDOWNLOADING_FILE_PATH # Band 1 from image" >> $METADATA_FILE_PATH
echo "$B2_INPUTDOWNLOADING_FILE_PATH # Band 2 from image" >> $METADATA_FILE_PATH
echo "$B3_INPUTDOWNLOADING_FILE_PATH # Band 3 from image" >> $METADATA_FILE_PATH
echo "$B4_INPUTDOWNLOADING_FILE_PATH # Band 4 from image" >> $METADATA_FILE_PATH
echo "$B5_INPUTDOWNLOADING_FILE_PATH # Band 5 from image" >> $METADATA_FILE_PATH
if [ $IMAGE_DATASET == "landsat_5" ] || [ $IMAGE_DATASET == "landsat_8" ]
then
  echo "$B6_INPUTDOWNLOADING_FILE_PATH # Band 6 from image" >> $METADATA_FILE_PATH
fi
if [ $IMAGE_DATASET == "landsat_7" ]
then
  echo "$B6_VCID_1_INPUTDOWNLOADING_FILE_PATH # Band 6 VCID 1 from image" >> $METADATA_FILE_PATH
  echo "$B6_VCID_2_INPUTDOWNLOADING_FILE_PATH # Band 6 VCID 2 from image" >> $METADATA_FILE_PATH
fi
echo "$B7_INPUTDOWNLOADING_FILE_PATH # Band 7 from image" >> $METADATA_FILE_PATH
if [ $IMAGE_DATASET == "landsat_7" ]
then
  echo "$B8_INPUTDOWNLOADING_FILE_PATH # Band 8 from image" >> $METADATA_FILE_PATH
fi
if [ $IMAGE_DATASET == "landsat_8" ]
then
  echo "$B8_INPUTDOWNLOADING_FILE_PATH # Band 8 from image" >> $METADATA_FILE_PATH
  echo "$B9_INPUTDOWNLOADING_FILE_PATH # Band 9 from image" >> $METADATA_FILE_PATH
  echo "$B10_INPUTDOWNLOADING_FILE_PATH # Band 10 from image" >> $METADATA_FILE_PATH
  echo "$B11_INPUTDOWNLOADING_FILE_PATH # Band 11 from image" >> $METADATA_FILE_PATH
fi
echo "$BQA_INPUTDOWNLOADING_FILE_PATH # Band QA from image" >> $METADATA_FILE_PATH
echo "$MTL_INPUTDOWNLOADING_FILE_PATH # MTL from image" >> $METADATA_FILE_PATH
echo "$STATION_INPUTDOWNLOADING_FILE_PATH # Station data from image" >> $METADATA_FILE_PATH
echo "$ELEVATION_RASTER_INPUTDOWNLOADING_FILE_PATH # Elevation raster data file path" >> $METADATA_FILE_PATH
